from __future__ import annotations

from slop_cop.rules.builtins._helpers import phrase_rule, regex_rule

RULES = (
    regex_rule(
        "rhetoric.not-but",
        "rhetoric",
        "Repeated contrast frame",
        "The sentence uses a formulaic not-X-but-Y contrast.",
        "State the distinction directly or keep only the meaningful contrast.",
        r"\bnot\s+(?:merely\s+|simply\s+)?[^.!?;:\n]{1,100}?\s*,?\s+but\s+(?:rather\s+)?\b",
        score_group="contrast",
    ),
    regex_rule(
        "rhetoric.not-just",
        "rhetoric",
        "Not-just frame",
        "The sentence uses a not-just setup that can become repetitive.",
        "Name the broader property directly when the contrast adds little.",
        r"\bnot\s+just\b",
        score_group="contrast",
        overlap_priority=10,
    ),
    regex_rule(
        "rhetoric.no-no",
        "rhetoric",
        "Parallel no frame",
        "A repeated no-X-no-Y frame emphasizes form over information.",
        "Replace the parallel negation with a precise description.",
        r"(?:^|[.!?]\s+)no\s+[^,.!?\n]{1,50},\s+no\s+[^.!?\n]{1,50}",
    ),
    regex_rule(
        "rhetoric.imperative-reframe",
        "rhetoric",
        "Imperative reframe",
        "The sentence uses a slogan-like command to reframe an action.",
        "Describe the recommended action and its reason directly.",
        r"\bdon['’]t\s+([\p{L}][\p{L}-]*)\s+it\s*[,;:—-]\s*[\p{L}][\p{L}-]*\s+it\b",
    ),
    regex_rule(
        "rhetoric.dramatic-fragment",
        "rhetoric",
        "Dramatic fragment",
        "A short question fragment creates a canned reveal.",
        "Join the fragment to the claim or state the claim directly.",
        r"(?:^|[.!?]\s+)(?:the\s+)?(?:punchline|kicker|twist|catch)\s*\?",
    ),
    phrase_rule(
        "rhetoric.throat-clearing",
        "rhetoric",
        "Throat clearing",
        "The phrase delays the substantive claim.",
        "Remove the introductory phrase and lead with the claim.",
        "it is important to note",
        "it is worth noting",
        "worth noting",
        "worth mentioning",
        "worth naming",
    ),
    phrase_rule(
        "rhetoric.testament",
        "rhetoric",
        "Testament claim",
        "The phrase praises an outcome without explaining its cause.",
        "Name the concrete evidence and what it demonstrates.",
        "a testament to",
        "stands as a testament to",
    ),
    phrase_rule(
        "rhetoric.crucial-role",
        "rhetoric",
        "Crucial-role claim",
        "The phrase asserts importance without describing the mechanism.",
        "Explain the component's specific responsibility or effect.",
        "plays a crucial role",
        "plays a pivotal role",
    ),
    regex_rule(
        "rhetoric.landscape-metaphor",
        "rhetoric",
        "Landscape metaphor",
        "A stock landscape metaphor replaces a concrete description of change.",
        "Describe the systems, constraints, or changes directly.",
        r"\b(?:ever[- ]evolving|rapidly changing|complex|dynamic)\s+"
        r"(?:technical\s+|digital\s+)?landscape\b",
    ),
    regex_rule(
        "rhetoric.formulaic-certainty",
        "rhetoric",
        "Formulaic certainty",
        "The phrase asserts shared certainty instead of providing evidence.",
        "State the evidence or limit the claim to what the note establishes.",
        r"\b(?:as (?:we|you) (?:all )?(?:know|understand)|you already know|the truth is)\b",
    ),
    regex_rule(
        "rhetoric.parallel-negation",
        "rhetoric",
        "Parallel negation",
        "Several parallel negations create a repetitive rhetorical cadence.",
        "Combine the negative clauses and emphasize the positive result.",
        r"\b(?:did|does|do|is|are|was|were)\s+not\b[^.!?\n]{0,80}\b(?:did|does|do|is|are|was|were)\s+not\b",
    ),
)
