#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail
umask 077

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"
ENV_FILE="$SCRIPT_DIR/runtime/demo.env"
[ -s "$ENV_FILE" ] || { echo "run ./run.sh once to provision the real gateway and sandbox" >&2; exit 1; }
# Generated by run.sh, mode 0600, and ignored by Git.
# shellcheck disable=SC1090
source "$ENV_FILE"

COMPOSE=(docker compose --env-file "$ENV_FILE" -f "$SCRIPT_DIR/compose.yaml")
control() { "${COMPOSE[@]}" run --rm control "$@"; }
sandbox_ssh_exec() {
  "${COMPOSE[@]}" run --rm --entrypoint /demo/control/sandbox-ssh-exec.sh control "$@"
}

control sandbox get hermes-demo --output json >"$SCRIPT_DIR/runtime/sandbox.json"
current_sandbox_id=$(jq -r '.metadata.id // .id // .sandbox.metadata.id // empty' "$SCRIPT_DIR/runtime/sandbox.json")
[ "$current_sandbox_id" = "$OPENSHELL_DEMO_SANDBOX_ID" ] || {
  echo "the persisted sandbox ID does not match the live OpenShell sandbox" >&2
  exit 1
}
hermes_exec() {
  local identity_args=(
    --env "HERMES_OPENSHELL_SANDBOX_ID=$OPENSHELL_DEMO_SANDBOX_ID"
    --env "HERMES_OPENSHELL_SANDBOX_NAME=hermes-demo"
  )
  if [ -n "${OPENSHELL_DEMO_POLICY_VERSION:-}" ]; then
    identity_args+=(--env "HERMES_OPENSHELL_POLICY_VERSION=$OPENSHELL_DEMO_POLICY_VERSION")
  fi
  control sandbox exec --name hermes-demo "${identity_args[@]}" "$@"
}
append_task_state() {
  awk -F= '
    $1 != "DEMO_REPOSITORY_COMMIT" &&
    $1 != "DEMO_EXPORTER_VERSION" &&
    $1 != "DEMO_BUILD_CREATED" &&
    $1 != "DEMO_TASK_STARTED_AT" &&
    $1 != "DEMO_TASK_FINISHED_AT" &&
    $1 != "DEMO_TASK_FILE_SHA256" &&
    $1 != "DEMO_AGENT_SESSION_ID" &&
    $1 != "DEMO_RELAY_SESSION_INSTANCE_ID"
  ' "$ENV_FILE" >"$ENV_FILE.tmp"
  {
    printf 'DEMO_REPOSITORY_COMMIT=%s\n' "$DEMO_REPOSITORY_COMMIT"
    printf 'DEMO_EXPORTER_VERSION=%s\n' "$DEMO_EXPORTER_VERSION"
    printf 'DEMO_BUILD_CREATED=%s\n' "$DEMO_BUILD_CREATED"
    printf 'DEMO_TASK_STARTED_AT=%s\n' "$DEMO_TASK_STARTED_AT"
    printf 'DEMO_TASK_FINISHED_AT=%s\n' "$DEMO_TASK_FINISHED_AT"
    printf 'DEMO_TASK_FILE_SHA256=%s\n' "$DEMO_TASK_FILE_SHA256"
    printf 'DEMO_AGENT_SESSION_ID=%s\n' "$DEMO_AGENT_SESSION_ID"
    printf 'DEMO_RELAY_SESSION_INSTANCE_ID=%s\n' "$DEMO_RELAY_SESSION_INSTANCE_ID"
  } >>"$ENV_FILE.tmp"
  mv "$ENV_FILE.tmp" "$ENV_FILE"
  chmod 0600 "$ENV_FILE"
}

sandbox_ssh_exec hermes-demo /usr/bin/rm -f /sandbox/showcase-agent-evidence.txt
sandbox_ssh_exec hermes-demo /usr/bin/test ! -e /sandbox/showcase-agent-evidence.txt
DEMO_REPOSITORY_COMMIT=$(git -C "$SCRIPT_DIR" rev-parse HEAD)
DEMO_EXPORTER_VERSION=$("$SCRIPT_DIR/../../../scripts/check-version.sh")
DEMO_BUILD_CREATED=$(git -C "$SCRIPT_DIR" show -s --format=%cI HEAD)
DEMO_TASK_STARTED_AT=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
DEMO_TASK_FINISHED_AT=
DEMO_TASK_FILE_SHA256=
DEMO_AGENT_SESSION_ID=
DEMO_RELAY_SESSION_INSTANCE_ID=
append_task_state

PROMPT=${HERMES_DEMO_PROMPT:-"Use the terminal tool to create /sandbox/showcase-agent-evidence.txt containing the non-secret text OpenShell exporter SOC showcase. Report the operating system and current working directory. Then explain in two sentences why a SOC should correlate agent telemetry with sandbox enforcement evidence."}
HERMES_RUN_LOG="$SCRIPT_DIR/runtime/hermes-run.log"
: >"$HERMES_RUN_LOG"
chmod 0600 "$HERMES_RUN_LOG"
echo "Running a fresh real Hermes/Nemotron task through the active exporter..."
hermes_exec --workdir /sandbox --timeout 300 --no-tty -- \
  hermes-correlated chat --query "$PROMPT" \
  --provider custom --model nvidia/nemotron-3-super-120b-a12b 2>&1 | tee "$HERMES_RUN_LOG"

DEMO_AGENT_SESSION_ID=$(sed -n 's/.*Session:[[:space:]]*\([A-Za-z0-9._:-][A-Za-z0-9._:-]*\).*/\1/p' "$HERMES_RUN_LOG" | tail -n 1)
[[ "$DEMO_AGENT_SESSION_ID" =~ ^[A-Za-z0-9._:-]{1,256}$ ]] \
  || { echo "could not capture the Hermes session ID" >&2; exit 1; }
atif_documents=$(sandbox_ssh_exec hermes-demo /bin/cat '/sandbox/telemetry/atif/hermes-atif-*.json')
DEMO_RELAY_SESSION_INSTANCE_ID=$(printf '%s\n' "$atif_documents" | jq -sr --arg session "$DEMO_AGENT_SESSION_ID" '
  [.[] | select([.extra.observed_events[]? | .data.session_id?, .metadata.session_id?] | index($session) != null)
    | .extra.nemo_relay.session_instance_id // empty]
  | unique
  | if length == 1 then .[0] else empty end
')
unset atif_documents
[[ "$DEMO_RELAY_SESSION_INSTANCE_ID" =~ ^[A-Za-z0-9._:-]{1,256}$ ]] \
  || { echo "could not prove the Hermes-to-Relay session bridge from ATIF" >&2; exit 1; }

sandbox_ssh_exec hermes-demo /usr/bin/test -s /sandbox/showcase-agent-evidence.txt
file_hash_output=$(sandbox_ssh_exec hermes-demo /usr/bin/sha256sum /sandbox/showcase-agent-evidence.txt)
DEMO_TASK_FILE_SHA256=$(printf '%s\n' "$file_hash_output" | awk '/^[0-9a-f]{64}[[:space:]]/ {print $1; exit}')
[[ "$DEMO_TASK_FILE_SHA256" =~ ^[0-9a-f]{64}$ ]] \
  || { echo "could not prove the created file identity" >&2; exit 1; }
[ "$DEMO_TASK_FILE_SHA256" != e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 ] \
  || { echo "the created showcase file is empty" >&2; exit 1; }

sandbox_ssh_exec hermes-demo \
  /usr/bin/curl --fail --silent --show-error https://example.com/ >/dev/null 2>&1 || true
DEMO_TASK_FINISHED_AT=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
append_task_state
echo "Waiting for the current evidence pipeline to settle..."
sleep 5
./verify.sh
