#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail
umask 077

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"
./preflight.sh

REQUESTED_EXTERNAL_DESTINATIONS=${DEMO_EXTERNAL_DESTINATIONS:-}
REQUESTED_DEMO_METRICS_PORT=${DEMO_METRICS_PORT:-}
REQUESTED_DEMO_HEALTH_PORT=${DEMO_HEALTH_PORT:-}
REQUESTED_EXTERNAL_CLOUDEVENTS_URL=${DEMO_EXTERNAL_CLOUDEVENTS_URL:-}
REQUESTED_EXTERNAL_OTLP_HTTP_ENDPOINT=${DEMO_EXTERNAL_OTLP_HTTP_ENDPOINT:-}
REQUESTED_EXTERNAL_TOKEN_FILE=${DEMO_EXTERNAL_TOKEN_FILE:-}
REQUESTED_EXTERNAL_CA_FILE=${DEMO_EXTERNAL_CA_FILE:-}

REPO_ROOT=$(cd -- "$SCRIPT_DIR/../../.." && pwd)

RUNTIME_DIR="$SCRIPT_DIR/runtime"
ENV_FILE="$RUNTIME_DIR/demo.env"
TLS_DIR="$RUNTIME_DIR/tls"
mkdir -p "$TLS_DIR" "$RUNTIME_DIR/state" "$RUNTIME_DIR/recovery" "$RUNTIME_DIR/gateway" "$RUNTIME_DIR/jwt"
HOST_CA_BUNDLE="$TLS_DIR/host-ca-certificates.crt"
case "$(uname -s)" in
  Linux)
    if [ -s /etc/ssl/certs/ca-certificates.crt ]; then
      cp /etc/ssl/certs/ca-certificates.crt "$HOST_CA_BUNDLE"
    elif [ -s /etc/ssl/cert.pem ]; then
      cp /etc/ssl/cert.pem "$HOST_CA_BUNDLE"
    else
      echo "host CA bundle is missing" >&2
      exit 1
    fi
    ;;
  Darwin)
    if [ -s /etc/ssl/cert.pem ]; then
      cp /etc/ssl/cert.pem "$HOST_CA_BUNDLE"
    else
      : >"$HOST_CA_BUNDLE"
    fi
    for keychain in \
      /System/Library/Keychains/SystemRootCertificates.keychain \
      /Library/Keychains/System.keychain; do
      [ -r "$keychain" ] || continue
      security find-certificate -a -p "$keychain" >>"$HOST_CA_BUNDLE" 2>/dev/null || true
    done
    ;;
  *)
    echo "unsupported host operating system for CA discovery: $(uname -s)" >&2
    exit 1
    ;;
esac
grep -q -- "-----BEGIN CERTIFICATE-----" "$HOST_CA_BUNDLE" \
  || { echo "host CA bundle contains no PEM certificates" >&2; exit 1; }
chmod 0600 "$HOST_CA_BUNDLE"
"$SCRIPT_DIR/control/prepare-build-context.sh" "$HOST_CA_BUNDLE"
if [ ! -s "$RUNTIME_DIR/jwt/signing.pem" ] || [ ! -s "$RUNTIME_DIR/jwt/public.pem" ] || [ ! -s "$RUNTIME_DIR/jwt/kid" ]; then
  openssl genpkey -algorithm Ed25519 -out "$RUNTIME_DIR/jwt/signing.pem"
  openssl pkey -in "$RUNTIME_DIR/jwt/signing.pem" -pubout -out "$RUNTIME_DIR/jwt/public.pem"
  openssl rand -hex 16 >"$RUNTIME_DIR/jwt/kid"
fi
chmod 0600 "$RUNTIME_DIR/jwt/signing.pem"
chmod 0644 "$RUNTIME_DIR/jwt/public.pem" "$RUNTIME_DIR/jwt/kid"

if [ -f "$ENV_FILE" ]; then
  # Generated by this script, mode 0600, and ignored by Git.
  # shellcheck disable=SC1090
  source "$ENV_FILE"
else
  NEMO_RELAY_OTLP_TOKEN=$(openssl rand -hex 32)
  WEBAPP_INGEST_TOKEN=$(openssl rand -hex 32)
  OPENSHELL_DEMO_SANDBOX_ID=pending
fi
# Runtime state may preserve credentials and evidence coordinates, but build
# identity must always describe the currently checked-out candidate.
DEMO_REPOSITORY_COMMIT=$(git -C "$REPO_ROOT" rev-parse HEAD)
DEMO_EXPORTER_VERSION=$("$REPO_ROOT/scripts/check-version.sh")
DEMO_BUILD_CREATED=$(git -C "$REPO_ROOT" show -s --format=%cI HEAD)
OPENSHELL_DEMO_POLICY_VERSION=${OPENSHELL_DEMO_POLICY_VERSION:-}
DEMO_TASK_STARTED_AT=${DEMO_TASK_STARTED_AT:-}
DEMO_TASK_FINISHED_AT=${DEMO_TASK_FINISHED_AT:-}
DEMO_TASK_FILE_SHA256=${DEMO_TASK_FILE_SHA256:-}
DEMO_AGENT_SESSION_ID=${DEMO_AGENT_SESSION_ID:-}
DEMO_RELAY_SESSION_INSTANCE_ID=${DEMO_RELAY_SESSION_INSTANCE_ID:-}
DEMO_EXTERNAL_DESTINATIONS=${REQUESTED_EXTERNAL_DESTINATIONS:-${DEMO_EXTERNAL_DESTINATIONS:-false}}
DEMO_EXTERNAL_CLOUDEVENTS_URL=${REQUESTED_EXTERNAL_CLOUDEVENTS_URL:-${DEMO_EXTERNAL_CLOUDEVENTS_URL:-}}
DEMO_EXTERNAL_OTLP_HTTP_ENDPOINT=${REQUESTED_EXTERNAL_OTLP_HTTP_ENDPOINT:-${DEMO_EXTERNAL_OTLP_HTTP_ENDPOINT:-}}
DEMO_EXTERNAL_CA_FILE=
case "$DEMO_EXTERNAL_DESTINATIONS" in
  true)
    [[ "$DEMO_EXTERNAL_CLOUDEVENTS_URL" =~ ^https://[A-Za-z0-9.-]+(:[0-9]{1,5})?(/[A-Za-z0-9._~:/?=%+@,-]*)?/v1/events$ ]] \
      || { echo "DEMO_EXTERNAL_CLOUDEVENTS_URL must be a shell-safe HTTPS URL ending in /v1/events" >&2; exit 1; }
    [[ "$DEMO_EXTERNAL_OTLP_HTTP_ENDPOINT" =~ ^https://[A-Za-z0-9.-]+(:[0-9]{1,5})?(/[A-Za-z0-9._~:/?=%+@,-]*)?$ ]] \
      || { echo "DEMO_EXTERNAL_OTLP_HTTP_ENDPOINT must be a shell-safe HTTPS OTLP base endpoint" >&2; exit 1; }
    external_token_path="$TLS_DIR/external-destination-token"
    if [ -n "$REQUESTED_EXTERNAL_TOKEN_FILE" ]; then
      [ -r "$REQUESTED_EXTERNAL_TOKEN_FILE" ] || { echo "DEMO_EXTERNAL_TOKEN_FILE is not readable" >&2; exit 1; }
      cp "$REQUESTED_EXTERNAL_TOKEN_FILE" "$external_token_path"
      chmod 0600 "$external_token_path"
    fi
    [ -s "$external_token_path" ] || { echo "DEMO_EXTERNAL_TOKEN_FILE is required for first external run" >&2; exit 1; }
    external_destination_token=$(<"$external_token_path")
    [ "${#external_destination_token}" -ge 32 ] \
      || { echo "external destination bearer token must contain at least 32 bytes" >&2; exit 1; }
    [[ "$external_destination_token" =~ ^[A-Za-z0-9._~+/-]+$ ]] \
      || { echo "external destination bearer token contains unsupported characters" >&2; exit 1; }
    external_ca_path="$TLS_DIR/external-destination-ca.crt"
    if [ -n "$REQUESTED_EXTERNAL_CA_FILE" ]; then
      [ -r "$REQUESTED_EXTERNAL_CA_FILE" ] || { echo "DEMO_EXTERNAL_CA_FILE is not readable" >&2; exit 1; }
      grep -q -- "-----BEGIN CERTIFICATE-----" "$REQUESTED_EXTERNAL_CA_FILE" \
        || { echo "DEMO_EXTERNAL_CA_FILE contains no PEM certificate" >&2; exit 1; }
      cp "$REQUESTED_EXTERNAL_CA_FILE" "$external_ca_path"
      chmod 0600 "$external_ca_path"
    fi
    [ -s "$external_ca_path" ] || { echo "DEMO_EXTERNAL_CA_FILE is required for first external run" >&2; exit 1; }
    DEMO_EXTERNAL_CA_FILE=/run/secrets/external-destination-ca.crt
    ;;
  false)
    DEMO_EXTERNAL_CLOUDEVENTS_URL=
    DEMO_EXTERNAL_OTLP_HTTP_ENDPOINT=
    ;;
  *)
    echo "DEMO_EXTERNAL_DESTINATIONS must be true or false" >&2
    exit 1
    ;;
esac
DEMO_GATEWAY_DATA_DIR=${DEMO_GATEWAY_DATA_DIR:-$RUNTIME_DIR/gateway}
DEMO_METRICS_PORT=${REQUESTED_DEMO_METRICS_PORT:-${DEMO_METRICS_PORT:-8888}}
DEMO_HEALTH_PORT=${REQUESTED_DEMO_HEALTH_PORT:-${DEMO_HEALTH_PORT:-13133}}
for port_name in DEMO_METRICS_PORT DEMO_HEALTH_PORT; do
  port=${!port_name}
  [[ "$port" =~ ^[0-9]{1,5}$ ]] && (( 10#$port > 0 && 10#$port <= 65535 )) \
    || { echo "$port_name must be a port between 1 and 65535" >&2; exit 1; }
done
docker_socket_uri=$(docker context inspect "$(docker context show)" --format '{{ (index .Endpoints "docker").Host }}')
case "$docker_socket_uri" in
  unix://*) detected_docker_socket=${docker_socket_uri#unix://} ;;
  *) echo "the active Docker context must use a Unix socket, got: $docker_socket_uri" >&2; exit 1 ;;
esac
DEMO_DOCKER_SOCKET=$detected_docker_socket
DEMO_UID=$(id -u)
DEMO_GID=$(id -g)

write_env() {
  {
    printf 'DEMO_GATEWAY_DATA_DIR=%s\n' "$DEMO_GATEWAY_DATA_DIR"
    printf 'DEMO_METRICS_PORT=%s\n' "$DEMO_METRICS_PORT"
    printf 'DEMO_HEALTH_PORT=%s\n' "$DEMO_HEALTH_PORT"
    printf 'DEMO_DOCKER_SOCKET=%s\n' "$DEMO_DOCKER_SOCKET"
    printf 'DEMO_UID=%s\n' "$DEMO_UID"
    printf 'DEMO_GID=%s\n' "$DEMO_GID"
    printf 'DEMO_REPOSITORY_COMMIT=%s\n' "$DEMO_REPOSITORY_COMMIT"
    printf 'DEMO_EXPORTER_VERSION=%s\n' "$DEMO_EXPORTER_VERSION"
    printf 'DEMO_BUILD_CREATED=%s\n' "$DEMO_BUILD_CREATED"
    printf 'NEMO_RELAY_OTLP_TOKEN=%s\n' "$NEMO_RELAY_OTLP_TOKEN"
    printf 'WEBAPP_INGEST_TOKEN=%s\n' "$WEBAPP_INGEST_TOKEN"
    printf 'OPENSHELL_DEMO_SANDBOX_ID=%s\n' "$OPENSHELL_DEMO_SANDBOX_ID"
    printf 'OPENSHELL_DEMO_POLICY_VERSION=%s\n' "$OPENSHELL_DEMO_POLICY_VERSION"
    printf 'DEMO_TASK_STARTED_AT=%s\n' "$DEMO_TASK_STARTED_AT"
    printf 'DEMO_TASK_FINISHED_AT=%s\n' "$DEMO_TASK_FINISHED_AT"
    printf 'DEMO_TASK_FILE_SHA256=%s\n' "$DEMO_TASK_FILE_SHA256"
    printf 'DEMO_AGENT_SESSION_ID=%s\n' "$DEMO_AGENT_SESSION_ID"
    printf 'DEMO_RELAY_SESSION_INSTANCE_ID=%s\n' "$DEMO_RELAY_SESSION_INSTANCE_ID"
    printf 'DEMO_EXTERNAL_DESTINATIONS=%s\n' "$DEMO_EXTERNAL_DESTINATIONS"
    printf 'DEMO_EXTERNAL_CLOUDEVENTS_URL=%s\n' "$DEMO_EXTERNAL_CLOUDEVENTS_URL"
    printf 'DEMO_EXTERNAL_OTLP_HTTP_ENDPOINT=%s\n' "$DEMO_EXTERNAL_OTLP_HTTP_ENDPOINT"
    printf 'DEMO_EXTERNAL_CA_FILE=%s\n' "$DEMO_EXTERNAL_CA_FILE"
  } >"$ENV_FILE"
  chmod 0600 "$ENV_FILE"
}
write_env

ca_regenerated=false
if [ ! -s "$TLS_DIR/ca.crt" ] || [ ! -s "$TLS_DIR/ca.key" ]; then
  openssl req -x509 -newkey rsa:3072 -sha256 -nodes -days 30 \
    -subj "/CN=OpenShell Exporter Demo CA" \
    -keyout "$TLS_DIR/ca.key" -out "$TLS_DIR/ca.crt" >/dev/null 2>&1
  ca_regenerated=true
fi

generate_server_certificate() {
  local name=$1
  local common_name=$2
  local subject_alt_name=$3
  openssl req -newkey rsa:3072 -sha256 -nodes \
    -subj "/CN=$common_name" \
    -keyout "$TLS_DIR/$name.key" -out "$TLS_DIR/$name.csr" >/dev/null 2>&1
  printf 'subjectAltName=%s\nextendedKeyUsage=serverAuth\n' "$subject_alt_name" >"$TLS_DIR/$name.ext"
  openssl x509 -req -sha256 -days 30 \
    -in "$TLS_DIR/$name.csr" \
    -CA "$TLS_DIR/ca.crt" -CAkey "$TLS_DIR/ca.key" -CAcreateserial \
    -extfile "$TLS_DIR/$name.ext" \
    -out "$TLS_DIR/$name.crt" >/dev/null 2>&1
}

if [ "$ca_regenerated" = true ] || [ ! -s "$TLS_DIR/exporter-server.crt" ] || [ ! -s "$TLS_DIR/exporter-server.key" ]; then
  generate_server_certificate \
    exporter-server \
    exporter.demo.internal \
    DNS:exporter.demo.internal,DNS:exporter
fi
if [ "$ca_regenerated" = true ] || [ ! -s "$TLS_DIR/conformance-receiver.crt" ] || [ ! -s "$TLS_DIR/conformance-receiver.key" ]; then
  generate_server_certificate \
    conformance-receiver \
    conformance-receiver.demo.internal \
    DNS:conformance-receiver.demo.internal,DNS:conformance-receiver,IP:127.0.0.1
fi
chmod 0600 "$TLS_DIR/ca.key" "$TLS_DIR/exporter-server.key" "$TLS_DIR/conformance-receiver.key"
chmod 0644 "$TLS_DIR/ca.crt" "$TLS_DIR/exporter-server.crt" "$TLS_DIR/conformance-receiver.crt"

COMPOSE=(docker compose --env-file "$ENV_FILE" -f "$SCRIPT_DIR/compose.yaml")
if [ "$DEMO_EXTERNAL_DESTINATIONS" = true ]; then
  COMPOSE+=(-f "$SCRIPT_DIR/compose.external.yaml")
fi
control() {
  "${COMPOSE[@]}" run --rm -e NVIDIA_API_KEY="$NVIDIA_API_KEY" control "$@"
}
sandbox_ssh_exec() {
  "${COMPOSE[@]}" run --rm \
    --entrypoint /demo/control/sandbox-ssh-exec.sh \
    control "$@"
}
wait_http() {
  local description=$1
  local url=$2
  local attempts=90
  while (( attempts > 0 )); do
    if curl --fail --silent --show-error "$url" >/dev/null 2>&1; then
      echo "$description is ready"
      return 0
    fi
    attempts=$((attempts - 1))
    sleep 1
  done
  echo "$description did not become ready: $url" >&2
  return 1
}
wait_https() {
  local description=$1
  local url=$2
  local ca_file=$3
  local attempts=90
  while (( attempts > 0 )); do
    if curl --fail --silent --show-error --cacert "$ca_file" "$url" >/dev/null 2>&1; then
      echo "$description is ready"
      return 0
    fi
    attempts=$((attempts - 1))
    sleep 1
  done
  echo "$description did not become ready: $url" >&2
  return 1
}

"${COMPOSE[@]}" build control hermes-image conformance-receiver exporter
HERMES_IMAGE_ID=$(docker image inspect --format "{{.Id}}" openshell-exporter-demo-hermes:0.20.2)
HERMES_IMAGE_REVISION=${HERMES_IMAGE_ID#sha256:}
HERMES_IMAGE_REVISION=${HERMES_IMAGE_REVISION:0:24}
[ "${#HERMES_IMAGE_REVISION}" -eq 24 ] || { echo "could not resolve Hermes image revision" >&2; exit 1; }
"${COMPOSE[@]}" up --detach gateway conformance-receiver
wait_http "OpenShell gateway" "http://127.0.0.1:8081/healthz"
wait_https "development conformance receiver" "https://127.0.0.1:8088/healthz" "$TLS_DIR/ca.crt"

docker volume inspect openshell-exporter-demo-ocsf >/dev/null 2>&1 \
  || docker volume create openshell-exporter-demo-ocsf >/dev/null

if control provider get nvidia-demo >/dev/null 2>&1; then
  control provider update nvidia-demo --from-existing >/dev/null
else
  control provider create --name nvidia-demo --type nvidia --from-existing >/dev/null
fi
control inference set \
  --provider nvidia-demo \
  --model nvidia/nemotron-3-super-120b-a12b \
  --timeout 300 >/dev/null
control settings set --global --yes --key ocsf_json_enabled --value true >/dev/null

sandbox_reusable=false
if control sandbox get hermes-demo --output json >"$RUNTIME_DIR/sandbox.json" 2>/dev/null; then
  sandbox_marker=$(jq -r ".labels.demo // empty" "$RUNTIME_DIR/sandbox.json")
  sandbox_image_revision=$(jq -r ".labels.demoimage // empty" "$RUNTIME_DIR/sandbox.json")
  if [ "$sandbox_marker" != "openshell-event-exporter" ]; then
    echo "refusing to replace hermes-demo because it is not owned by this demo" >&2
    exit 1
  elif [ "$sandbox_image_revision" = "$HERMES_IMAGE_REVISION" ]; then
    sandbox_reusable=true
  else
    echo "Replacing stale demo sandbox with Hermes image revision $HERMES_IMAGE_REVISION"
    control sandbox delete hermes-demo
  fi
fi

if [ "$sandbox_reusable" = true ]; then
  echo "Using current OpenShell sandbox hermes-demo"
else
  driver_config="{\"docker\":{\"mounts\":[{\"type\":\"volume\",\"source\":\"openshell-exporter-demo-ocsf\",\"target\":\"/var/log\",\"read_only\":false}]}}"
  control sandbox create \
    --name hermes-demo \
    --from openshell-exporter-demo-hermes:0.20.2 \
    --policy /demo/sandbox-policy.yaml \
    --driver-config-json "$driver_config" \
    --label demo=openshell-event-exporter \
    --label demoimage="$HERMES_IMAGE_REVISION" \
    --env "NEMO_RELAY_OTEL_AUTHORIZATION=Bearer $NEMO_RELAY_OTLP_TOKEN" \
    --no-auto-providers \
    --no-tty \
    --output json >"$RUNTIME_DIR/sandbox.json"
fi

# Refresh from the authorized gateway after create or reuse so optional status
# metadata comes from the current sandbox representation, not a stale response.
control sandbox get hermes-demo --output json >"$RUNTIME_DIR/sandbox.json"

OPENSHELL_DEMO_SANDBOX_ID=$(jq -r '.metadata.id // .id // .sandbox.metadata.id // empty' "$RUNTIME_DIR/sandbox.json")
[ -n "$OPENSHELL_DEMO_SANDBOX_ID" ] || {
  echo "could not read sandbox ID from OpenShell response" >&2
  exit 1
}
OPENSHELL_DEMO_POLICY_VERSION=$(jq -r '
  [
    .status.current_policy_version,
    .status.currentPolicyVersion,
    .status.policy_version,
    .status.policyVersion,
    .sandbox.status.current_policy_version,
    .sandbox.status.currentPolicyVersion,
    .sandbox.status.policy_version,
    .sandbox.status.policyVersion
  ]
  | map(select(. != null and (. | tostring) != "" and (. | tostring) != "0"))
  | first // empty
  | tostring
' "$RUNTIME_DIR/sandbox.json")
case "$OPENSHELL_DEMO_POLICY_VERSION" in
  ""|*[!0-9]*)
    if [ -n "$OPENSHELL_DEMO_POLICY_VERSION" ]; then
      echo "OpenShell returned an invalid current policy version" >&2
      exit 1
    fi
    ;;
  *) ;;
esac
write_env

# OpenShell 0.0.113 reserves OPENSHELL_* keys and does not inject a sandbox ID
# into sandbox exec processes. Bind the authoritative ID returned by sandbox
# get/create to every Hermes exec through launcher-owned, non-secret variables,
# rather than relying on an operator-configured or workload-invented identifier.
hermes_exec() {
  local identity_args=(
    --env "HERMES_OPENSHELL_SANDBOX_ID=$OPENSHELL_DEMO_SANDBOX_ID"
    --env "HERMES_OPENSHELL_SANDBOX_NAME=hermes-demo"
  )
  if [ -n "$OPENSHELL_DEMO_POLICY_VERSION" ]; then
    identity_args+=(--env "HERMES_OPENSHELL_POLICY_VERSION=$OPENSHELL_DEMO_POLICY_VERSION")
  fi
  control sandbox exec --name hermes-demo "${identity_args[@]}" "$@"
}

if [ "$sandbox_reusable" = false ]; then
  hermes_exec --workdir /sandbox --timeout 60 --no-tty -- \
    /usr/local/bin/hermes-correlated --version
fi

"${COMPOSE[@]}" up --detach exporter
wait_http "OpenShell event exporter" "http://127.0.0.1:$DEMO_HEALTH_PORT/"

# A reused demo sandbox must not satisfy the task with a prior run's artifact.
sandbox_ssh_exec hermes-demo /usr/bin/rm -f /sandbox/showcase-agent-evidence.txt
sandbox_ssh_exec hermes-demo /usr/bin/test ! -e /sandbox/showcase-agent-evidence.txt

DEMO_TASK_STARTED_AT=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
DEMO_TASK_FINISHED_AT=
DEMO_AGENT_SESSION_ID=
DEMO_RELAY_SESSION_INSTANCE_ID=
write_env

PROMPT=${HERMES_DEMO_PROMPT:-"Use the terminal tool to create /sandbox/showcase-agent-evidence.txt containing the non-secret text OpenShell exporter showcase. Report the operating system, current working directory, and the first five entries in /sandbox. Attempt curl --fail --silent --show-error https://example.com/ once; the OpenShell policy denial is expected, so continue. Then explain in two sentences why an agent sandbox should export security evidence."}
HERMES_RUN_LOG="$RUNTIME_DIR/hermes-run.log"
: >"$HERMES_RUN_LOG"
chmod 0600 "$HERMES_RUN_LOG"
echo "Running the real Hermes/Nemotron task (OpenShell timeout: 300s)..."
(
  hermes_exec \
    --workdir /sandbox \
    --timeout 300 \
    --no-tty \
    -- hermes-correlated chat --query "$PROMPT" \
      --provider custom \
      --model nvidia/nemotron-3-super-120b-a12b 2>&1 | tee "$HERMES_RUN_LOG"
) &
hermes_task_pid=$!
hermes_elapsed=0
while kill -0 "$hermes_task_pid" 2>/dev/null; do
  sleep 15
  if kill -0 "$hermes_task_pid" 2>/dev/null; then
    hermes_elapsed=$((hermes_elapsed + 15))
    printf 'Hermes/Nemotron task is still running (%ss elapsed; timeout 300s)...\n' \
      "$hermes_elapsed"
  fi
done
if ! wait "$hermes_task_pid"; then
  echo "Hermes/Nemotron task failed or reached the OpenShell 300s timeout; inspect $HERMES_RUN_LOG" >&2
  exit 1
fi
DEMO_AGENT_SESSION_ID=$(sed -n 's/.*Session:[[:space:]]*\([A-Za-z0-9._:-][A-Za-z0-9._:-]*\).*/\1/p' "$HERMES_RUN_LOG" | tail -n 1)
[[ "$DEMO_AGENT_SESSION_ID" =~ ^[A-Za-z0-9._:-]{1,256}$ ]] \
  || { echo "could not capture the Hermes session ID" >&2; exit 1; }

# Hermes and NeMo Relay intentionally use different session namespaces. Read
# Hermes' ATIF artifact through the OpenShell SSH boundary and require its
# explicit bridge from the transcript session to the Relay session instance.
# The artifact can contain sensitive content, so retain only the two IDs in
# memory and never copy the ATIF body onto the host.
atif_documents=$(sandbox_ssh_exec hermes-demo \
  /bin/cat '/sandbox/telemetry/atif/hermes-atif-*.json')
DEMO_RELAY_SESSION_INSTANCE_ID=$(printf '%s\n' "$atif_documents" | jq -sr --arg session "$DEMO_AGENT_SESSION_ID" '
  [
    .[]
    | select(
        [.extra.observed_events[]? | .data.session_id?, .metadata.session_id?]
        | index($session) != null
      )
    | .extra.nemo_relay.session_instance_id // empty
  ]
  | unique
  | if length == 1 then .[0] else empty end
')
unset atif_documents
[[ "$DEMO_RELAY_SESSION_INSTANCE_ID" =~ ^[A-Za-z0-9._:-]{1,256}$ ]] \
  || { echo "could not prove the Hermes-to-Relay session bridge from ATIF" >&2; exit 1; }
write_env

echo "Proving the real sandbox artifact over OpenShell SSH..."
sandbox_ssh_exec hermes-demo \
  /usr/bin/test -s /sandbox/showcase-agent-evidence.txt
file_hash_output=$(sandbox_ssh_exec hermes-demo \
  /usr/bin/sha256sum /sandbox/showcase-agent-evidence.txt)
DEMO_TASK_FILE_SHA256=$(printf '%s\n' "$file_hash_output" | awk '/^[0-9a-f]{64}[[:space:]]/ {print $1; exit}')
[[ "$DEMO_TASK_FILE_SHA256" =~ ^[0-9a-f]{64}$ ]] \
  || { echo "could not prove the created file identity" >&2; exit 1; }
[ "$DEMO_TASK_FILE_SHA256" != e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 ] \
  || { echo "the created showcase file is empty" >&2; exit 1; }

# A real denied request makes the network-policy evidence lane visible. The
# denial is expected and is not converted into a fake fixture or event.
echo "Generating a real OpenShell network-policy denial..."
sandbox_ssh_exec hermes-demo \
  /usr/bin/curl --fail --silent --show-error https://example.com/ >/dev/null 2>&1 || true

DEMO_TASK_FINISHED_AT=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
write_env

echo "Waiting for the evidence pipeline to settle..."
sleep 5
echo "Verifying OpenShell and NeMo Relay correlation..."
./verify.sh

if [ "${DEMO_SUPPRESS_CONFORMANCE_UI:-false}" != true ]; then
  printf '\nDevelopment conformance receiver: https://127.0.0.1:8088\n'
  printf 'Trust %s only for this local fixture.\n' "$TLS_DIR/ca.crt"
  printf 'This fixture is for protocol verification and debugging, not the product UI.\n'
fi
printf 'Durable redacted recovery is under %s.\n' "$RUNTIME_DIR/recovery"
if [ "$DEMO_EXTERNAL_DESTINATIONS" = true ]; then
  printf 'External fan-out is enabled; export backend query projections and run ./verify-external.sh to prove the same timeline.\n'
fi
printf 'Stop containers and the sandbox with ./down.sh (evidence volumes are preserved).\n'
