# Generated by examples/demo/kubernetes/run.sh. Do not commit the rendered file.
profile: complete
image:
  repository: docker.io/local/openshell-event-exporter
  digest: EXPORTER_DIGEST
  pullPolicy: Never
source:
  endpoint: https://openshell.openshell.svc.cluster.local:8080
  gatewayId: omnistation-kubernetes-demo
  workspace: default
  sourceInstance: kubernetes-gateway
  authSecret: openshell-exporter-source-auth
  bearerEnabled: false
  tlsSecret: openshell-exporter-source-tls
  mtlsEnabled: true
files:
  openshell:
    enabled: false
  relay:
    enabled: false
relay:
  input:
    enabled: true
    mtlsEnabled: false
    authSecret: openshell-exporter-relay-input-auth
    tlsSecret: openshell-exporter-relay-input-tls
nativeOtlp:
  enabled: true
  tlsSecret: openshell-exporter-native-otlp-tls
forwardedOcsf:
  enabled: true
  authSecret: openshell-exporter-forwarded-ocsf-auth
  tlsSecret: openshell-exporter-forwarded-ocsf-tls
sandboxInjection:
  forwarderAuthSecret: openshell-exporter-forwarded-ocsf-auth
  enabled: true
  replicas: 1
  allowedNamespaces: [openshell-sandboxes]
  allowedGatewayUsernames: [system:serviceaccount:openshell:openshell]
  evidencePersistence:
    storageClass: csi-hostpath-sc
    size: 512Mi
  statePersistence:
    storageClass: csi-hostpath-sc
    size: 256Mi
certManager:
  enabled: true
  issuerRef:
    name: openshell-exporter-pki
    kind: ClusterIssuer
    group: cert-manager.io
kubernetesContext:
  enabled: true
  namespaces: [openshell, openshell-sandboxes]
networkPolicy:
  enabled: true
  additionalSourceNamespaces: [openshell, openshell-sandboxes]
  monitoringNamespaces: [openshell-observability]
destination:
  cloudEvents:
    endpoint: https://logstash.openshell-observability.svc.cluster.local:8443/v1/events
    authSecret: openshell-exporter-elastic-cloudevents-auth
    tlsSecret: openshell-elastic-logstash-client
    mtlsEnabled: true
  otlp:
    grpcEndpoint: apm-server.openshell-observability.svc.cluster.local:8200
    httpEndpoint: https://apm-server.openshell-observability.svc.cluster.local:8200
    authSecret: openshell-exporter-elastic-apm-auth
    tlsSecret: openshell-elastic-apm-server
    mtlsEnabled: false
persistence:
  queue: {storageClass: csi-hostpath-sc, size: 2Gi}
  recovery: {storageClass: csi-hostpath-sc, size: 2Gi}
  checkpoints: {storageClass: csi-hostpath-sc, size: 1Gi}
  otlpGrpcQueue: {storageClass: csi-hostpath-sc, size: 2Gi}
  otlpHttpQueue: {storageClass: csi-hostpath-sc, size: 2Gi}
resources:
  requests: {cpu: 100m, memory: 256Mi}
  limits: {cpu: "2", memory: 1Gi}
