# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""First-class harness admission and attested-egress APIs."""

from egress_gate.admission.adapters import (
    AttestedCandidate,
    HarnessAdapter,
    HarnessAdapterRegistry,
    OpenAIChatCompletionsV1Adapter,
    OpenAIResponsesV1Adapter,
    PiImageContentV1,
    PiInputV1,
    PiTextContentV1,
    PiToolResultV1,
    PiToolResultV1Adapter,
    PiV1Adapter,
    PreparedHarnessRequest,
    ProviderAdapterRegistry,
    ProviderRequestAdapter,
    create_pi_adapter_registry,
    create_provider_adapter_registry,
)
from egress_gate.admission.canonical import (
    CanonicalFunctionCallV1,
    CanonicalGenerationV1,
    CanonicalMessageV1,
    CanonicalRole,
    CanonicalToolChoiceV1,
    CanonicalToolV1,
    ModelRequestV1,
    canonical_json_bytes,
)
from egress_gate.admission.models import (
    MAX_ADMISSION_BODY_BYTES,
    PI_HARNESS_VERSION,
    AdmissionDecision,
    AdmissionHook,
    AdmissionProvenance,
    HarnessAdmissionContext,
    HarnessAdmissionRequest,
    HarnessAdmissionResult,
)
from egress_gate.admission.processor import (
    RECEIPT_HEADER,
    AttestedEgressProcessor,
    HarnessAdmissionProcessor,
)
from egress_gate.admission.receipts import (
    AgentAttestationClaimsV1,
    ReceiptAuthority,
    ReceiptClaimsV1,
    ReceiptVerificationError,
)

__all__ = [
    "AdmissionDecision",
    "AdmissionHook",
    "AdmissionProvenance",
    "AgentAttestationClaimsV1",
    "AttestedCandidate",
    "AttestedEgressProcessor",
    "CanonicalFunctionCallV1",
    "CanonicalGenerationV1",
    "CanonicalMessageV1",
    "CanonicalRole",
    "CanonicalToolChoiceV1",
    "CanonicalToolV1",
    "HarnessAdapter",
    "HarnessAdapterRegistry",
    "HarnessAdmissionContext",
    "HarnessAdmissionProcessor",
    "HarnessAdmissionRequest",
    "HarnessAdmissionResult",
    "MAX_ADMISSION_BODY_BYTES",
    "PI_HARNESS_VERSION",
    "ModelRequestV1",
    "OpenAIChatCompletionsV1Adapter",
    "OpenAIResponsesV1Adapter",
    "PiInputV1",
    "PiImageContentV1",
    "PiTextContentV1",
    "PiToolResultV1",
    "PiToolResultV1Adapter",
    "PiV1Adapter",
    "PreparedHarnessRequest",
    "ProviderAdapterRegistry",
    "ProviderRequestAdapter",
    "RECEIPT_HEADER",
    "ReceiptAuthority",
    "ReceiptClaimsV1",
    "ReceiptVerificationError",
    "canonical_json_bytes",
    "create_pi_adapter_registry",
    "create_provider_adapter_registry",
]
