# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""First-class harness admission and attested-egress APIs."""

from egress_gate.admission.adapters import (
    AttestedEntries,
    ContextEntryV1,
    HarnessAdapter,
    HarnessAdapterRegistry,
    OpenAIChatCompletionsV1Adapter,
    OpenAIResponsesV1Adapter,
    PiAssistantMessageV1,
    PiAssistantMessageV1Adapter,
    PiAssistantToolCallV1,
    PiBashExecutionV1,
    PiBashExecutionV1Adapter,
    PiImageContentV1,
    PiMessageV1,
    PiMessageV1Adapter,
    PiProviderContextV1,
    PiProviderContextV1Adapter,
    PiTextContentV1,
    PiToolResultV1,
    PiToolResultV1Adapter,
    PreparedHarnessRequest,
    ProviderAdapterRegistry,
    ProviderRequestAdapter,
    ToolContextEntryV1,
    UserContextEntryV1,
    context_entries_subject,
    create_pi_adapter_registry,
    create_provider_adapter_registry,
)
from egress_gate.admission.canonical import (
    CanonicalFunctionCallV1,
    CanonicalGenerationV1,
    CanonicalMessageV1,
    CanonicalRole,
    CanonicalToolChoiceV1,
    CanonicalToolV1,
    ModelRequestV1,
    canonical_json_bytes,
)
from egress_gate.admission.models import (
    MAX_ADMISSION_BODY_BYTES,
    PI_HARNESS_VERSION,
    AdmissionDecision,
    AdmissionHook,
    AdmissionProvenance,
    HarnessAdmissionContext,
    HarnessAdmissionRequest,
    HarnessAdmissionResult,
)
from egress_gate.admission.processor import (
    RECEIPT_HEADER,
    AttestedEgressProcessor,
    HarnessAdmissionProcessor,
)
from egress_gate.admission.receipts import (
    AgentAttestationClaimsV2,
    ReceiptAuthority,
    ReceiptVerificationError,
)

__all__ = [
    "AdmissionDecision",
    "AdmissionHook",
    "AdmissionProvenance",
    "AgentAttestationClaimsV2",
    "AttestedEntries",
    "AttestedEgressProcessor",
    "CanonicalFunctionCallV1",
    "CanonicalGenerationV1",
    "CanonicalMessageV1",
    "CanonicalRole",
    "CanonicalToolChoiceV1",
    "CanonicalToolV1",
    "ContextEntryV1",
    "HarnessAdapter",
    "HarnessAdapterRegistry",
    "HarnessAdmissionContext",
    "HarnessAdmissionProcessor",
    "HarnessAdmissionRequest",
    "HarnessAdmissionResult",
    "MAX_ADMISSION_BODY_BYTES",
    "PI_HARNESS_VERSION",
    "ModelRequestV1",
    "OpenAIChatCompletionsV1Adapter",
    "OpenAIResponsesV1Adapter",
    "PiAssistantMessageV1",
    "PiAssistantMessageV1Adapter",
    "PiAssistantToolCallV1",
    "PiBashExecutionV1",
    "PiBashExecutionV1Adapter",
    "PiMessageV1",
    "PiImageContentV1",
    "PiTextContentV1",
    "PiToolResultV1",
    "PiToolResultV1Adapter",
    "PiMessageV1Adapter",
    "PiProviderContextV1",
    "PiProviderContextV1Adapter",
    "PreparedHarnessRequest",
    "ProviderAdapterRegistry",
    "ProviderRequestAdapter",
    "RECEIPT_HEADER",
    "ReceiptAuthority",
    "ReceiptVerificationError",
    "ToolContextEntryV1",
    "UserContextEntryV1",
    "canonical_json_bytes",
    "context_entries_subject",
    "create_pi_adapter_registry",
    "create_provider_adapter_registry",
]
