# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import supervisor_middleware_pb2 as supervisor__middleware__pb2

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in supervisor_middleware_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SupervisorMiddlewareStub:
    """SupervisorMiddleware lets an operator-run service inspect and transform
    sandbox HTTP egress before OpenShell injects credentials.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
            "/openshell.middleware.v1.SupervisorMiddleware/Describe",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=supervisor__middleware__pb2.MiddlewareManifest.FromString,
            _registered_method=True,
        )
        self.ValidateConfig = channel.unary_unary(
            "/openshell.middleware.v1.SupervisorMiddleware/ValidateConfig",
            request_serializer=supervisor__middleware__pb2.ValidateConfigRequest.SerializeToString,
            response_deserializer=supervisor__middleware__pb2.ValidateConfigResponse.FromString,
            _registered_method=True,
        )
        self.EvaluateHttpRequest = channel.unary_unary(
            "/openshell.middleware.v1.SupervisorMiddleware/EvaluateHttpRequest",
            request_serializer=supervisor__middleware__pb2.HttpRequestEvaluation.SerializeToString,
            response_deserializer=supervisor__middleware__pb2.HttpRequestResult.FromString,
            _registered_method=True,
        )


class SupervisorMiddlewareServicer:
    """SupervisorMiddleware lets an operator-run service inspect and transform
    sandbox HTTP egress before OpenShell injects credentials.
    """

    def Describe(self, request, context):
        """Describe returns the service manifest and declared bindings."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateConfig(self, request, context):
        """ValidateConfig checks service-specific configuration for one binding."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EvaluateHttpRequest(self, request, context):
        """EvaluateHttpRequest returns an allow, deny, or mutation decision for one
        buffered HTTP request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SupervisorMiddlewareServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Describe": grpc.unary_unary_rpc_method_handler(
            servicer.Describe,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=supervisor__middleware__pb2.MiddlewareManifest.SerializeToString,
        ),
        "ValidateConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateConfig,
            request_deserializer=supervisor__middleware__pb2.ValidateConfigRequest.FromString,
            response_serializer=supervisor__middleware__pb2.ValidateConfigResponse.SerializeToString,
        ),
        "EvaluateHttpRequest": grpc.unary_unary_rpc_method_handler(
            servicer.EvaluateHttpRequest,
            request_deserializer=supervisor__middleware__pb2.HttpRequestEvaluation.FromString,
            response_serializer=supervisor__middleware__pb2.HttpRequestResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "openshell.middleware.v1.SupervisorMiddleware", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "openshell.middleware.v1.SupervisorMiddleware", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class SupervisorMiddleware:
    """SupervisorMiddleware lets an operator-run service inspect and transform
    sandbox HTTP egress before OpenShell injects credentials.
    """

    @staticmethod
    def Describe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/openshell.middleware.v1.SupervisorMiddleware/Describe",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            supervisor__middleware__pb2.MiddlewareManifest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/openshell.middleware.v1.SupervisorMiddleware/ValidateConfig",
            supervisor__middleware__pb2.ValidateConfigRequest.SerializeToString,
            supervisor__middleware__pb2.ValidateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EvaluateHttpRequest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/openshell.middleware.v1.SupervisorMiddleware/EvaluateHttpRequest",
            supervisor__middleware__pb2.HttpRequestEvaluation.SerializeToString,
            supervisor__middleware__pb2.HttpRequestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
