apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openshell-event-exporter.fullname" . }}-config
  labels:
    {{- include "openshell-event-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ include "openshell-event-exporter.renderConfig" . | indent 4 }}
