export const homePosition = [-1.08, 0.78, 0.58];

export const policyPacks = [
  {
    id: "workspace",
    name: "Workspace bounds",
    tone: "green",
    invariant: "No path segment may leave the configured workcell.",
  },
  {
    id: "human",
    name: "Human proximity",
    tone: "amber",
    invariant: "Motion must slow near humans and stop inside the hard radius.",
  },
  {
    id: "materials",
    name: "Sample handling",
    tone: "cyan",
    invariant: "Fragile or hazardous samples require reduced speed and force.",
  },
  {
    id: "delegation",
    name: "Delegation",
    tone: "violet",
    invariant: "Subagents cannot expand authority beyond the parent grant.",
  },
  {
    id: "budget",
    name: "Budget envelope",
    tone: "rose",
    invariant: "Plans must stay inside time, action, and compute limits.",
  },
  {
    id: "audit",
    name: "Audit obligations",
    tone: "blue",
    invariant: "Every physical action must emit a durable decision record.",
  },
];

export const objects = [
  {
    id: "green-vial",
    label: "Green vial",
    color: "#31b66b",
    position: [-0.72, 0.18, -0.46],
    size: [0.18, 0.26, 0.18],
  },
  {
    id: "red-sample",
    label: "Red sample",
    color: "#e45454",
    position: [-0.22, 0.15, -0.68],
    size: [0.22, 0.2, 0.22],
  },
  {
    id: "yellow-core",
    label: "Yellow core",
    color: "#e7b92f",
    position: [0.26, 0.16, -0.48],
    size: [0.2, 0.22, 0.2],
  },
  {
    id: "blue-tray",
    label: "Blue tray",
    color: "#3f7dda",
    position: [0.83, 0.08, 0.28],
    size: [0.62, 0.08, 0.42],
  },
];

export const zones = [
  {
    id: "restricted",
    label: "Restricted",
    color: "#e44f5e",
    position: [0.22, 0.24, 0.04],
    size: [0.56, 0.48, 0.72],
  },
  {
    id: "caution",
    label: "Caution",
    color: "#e8b630",
    position: [-0.12, 0.15, -0.46],
    size: [0.96, 0.3, 0.56],
  },
];

export const scenarios = [
  {
    id: "normal-autonomy",
    label: "Normal",
    title: "Normal Autonomy",
    actor: "planner-agent",
    subagent: "motion-agent",
    action: "arm.move_path",
    object: "green-vial",
    resource: "so101.sim.arm",
    decision: "allow",
    risk: "Low",
    speed: "0.18 m/s",
    force: "2.1 N",
    solverMs: 6,
    budget: 84,
    compute: 21,
    remainingActions: 11,
    humanDistance: "1.42 m",
    sensorAge: "72 ms",
    proposedPath: [
      homePosition,
      [-0.86, 0.72, 0.12],
      [-0.72, 0.38, -0.46],
      [0.58, 0.46, 0.2],
      [0.83, 0.34, 0.28],
    ],
    approvedPath: [
      homePosition,
      [-0.86, 0.72, 0.12],
      [-0.72, 0.38, -0.46],
      [0.58, 0.46, 0.2],
      [0.83, 0.34, 0.28],
    ],
    human: { position: [1.1, 0.08, -0.72], radius: 0.22, caution: 0.52 },
    activePolicies: ["workspace", "audit"],
    constraints: ["Path remains inside workcell", "Decision record required"],
    obligations: ["Emit audit event", "Expire capability after 4s"],
    explanation:
      "The proposed move stays inside workspace bounds and uses an unprivileged object-handling grant.",
  },
  {
    id: "human-composition",
    label: "Human near",
    title: "Human Proximity Composition",
    actor: "planner-agent",
    subagent: "motion-agent",
    action: "arm.move_path",
    object: "red-sample",
    resource: "so101.sim.arm",
    decision: "constrain",
    risk: "Medium",
    speed: "0.42 -> 0.08 m/s",
    force: "3.8 -> 2.0 N",
    solverMs: 13,
    budget: 67,
    compute: 38,
    remainingActions: 7,
    humanDistance: "0.48 m",
    sensorAge: "88 ms",
    proposedPath: [
      homePosition,
      [-0.55, 0.62, -0.1],
      [-0.22, 0.34, -0.68],
      [0.34, 0.32, -0.12],
      [0.83, 0.34, 0.28],
    ],
    approvedPath: [
      homePosition,
      [-0.72, 0.82, 0.0],
      [-0.36, 0.62, -0.62],
      [0.12, 0.58, -0.5],
      [0.68, 0.52, 0.08],
      [0.83, 0.34, 0.28],
    ],
    human: { position: [0.12, 0.08, -0.18], radius: 0.28, caution: 0.68 },
    activePolicies: ["workspace", "human", "materials", "audit"],
    constraints: [
      "Clamp speed to <= 0.08 m/s",
      "Clamp gripper force to <= 2.0 N",
      "Route outside caution overlap",
    ],
    obligations: [
      "Pause if human_distance < 0.5 m",
      "Recheck before gripper.close",
      "Emit audit event",
    ],
    explanation:
      "Human proximity and fragile-sample policies both apply, so the action is allowed only as a slower alternate path.",
  },
  {
    id: "restricted-zone",
    label: "No-go zone",
    title: "Restricted Zone Denial",
    actor: "planner-agent",
    subagent: "motion-agent",
    action: "arm.move_path",
    object: "yellow-core",
    resource: "so101.sim.arm",
    decision: "deny",
    risk: "High",
    speed: "0.25 m/s",
    force: "3.2 N",
    solverMs: 10,
    budget: 59,
    compute: 44,
    remainingActions: 6,
    humanDistance: "1.08 m",
    sensorAge: "64 ms",
    proposedPath: [
      homePosition,
      [-0.44, 0.58, 0.08],
      [0.22, 0.34, 0.04],
      [0.7, 0.34, 0.22],
    ],
    approvedPath: [homePosition],
    human: { position: [1.08, 0.08, -0.62], radius: 0.24, caution: 0.52 },
    activePolicies: ["workspace", "materials", "audit"],
    constraints: ["No feasible path through restricted_zone"],
    obligations: ["Keep prior capability unchanged", "Record denial"],
    explanation:
      "The candidate trajectory intersects the restricted volume, and no override grant is present for that region.",
  },
  {
    id: "delegation",
    label: "Delegation",
    title: "Subagent Delegation Check",
    actor: "planner-agent",
    subagent: "cleanup-subagent",
    action: "grant.capability",
    object: "so101.sim.arm",
    resource: "delegated-motion-capability",
    decision: "deny",
    risk: "High",
    speed: "n/a",
    force: "n/a",
    solverMs: 17,
    budget: 46,
    compute: 56,
    remainingActions: 4,
    humanDistance: "0.93 m",
    sensorAge: "101 ms",
    proposedPath: [
      homePosition,
      [-0.62, 0.68, 0.32],
      [0.38, 0.44, -0.02],
      [0.92, 0.38, -0.42],
    ],
    approvedPath: [homePosition],
    human: { position: [0.92, 0.08, -0.48], radius: 0.24, caution: 0.52 },
    activePolicies: ["delegation", "human", "audit"],
    constraints: [
      "Parent grant excludes restricted_zone",
      "Child grant requested unrestricted move_path",
      "Delegated speed cap exceeds parent speed cap",
    ],
    obligations: ["Reject broader grant", "Record attempted escalation"],
    explanation:
      "The subagent requested a capability that is broader than its parent envelope, including restricted-zone access and a higher speed cap.",
  },
  {
    id: "budget",
    label: "Budget",
    title: "Budget-Constrained Autonomy",
    actor: "planner-agent",
    subagent: "optimizer-subagent",
    action: "plan.extend",
    object: "sorting-task",
    resource: "mission-budget",
    decision: "approval",
    risk: "Medium",
    speed: "0.12 m/s",
    force: "1.7 N",
    solverMs: 9,
    budget: 8,
    compute: 86,
    remainingActions: 1,
    humanDistance: "0.81 m",
    sensorAge: "79 ms",
    proposedPath: [
      homePosition,
      [-0.56, 0.8, -0.12],
      [-0.12, 0.56, -0.64],
      [0.68, 0.52, 0.12],
      [0.92, 0.34, 0.34],
    ],
    approvedPath: [
      homePosition,
      [-0.72, 0.72, -0.02],
      [0.42, 0.5, 0.12],
      [0.83, 0.34, 0.28],
    ],
    human: { position: [0.64, 0.08, -0.58], radius: 0.25, caution: 0.54 },
    activePolicies: ["budget", "workspace", "audit"],
    constraints: [
      "One final move may execute",
      "No replanning loop without supervisor approval",
      "Compute budget remains below 90%",
    ],
    obligations: ["Request supervisor approval for extension", "Close task after final move"],
    explanation:
      "The current task has enough budget for one bounded action, but continued optimization requires approval.",
  },
];

export function policyTone(id) {
  return policyPacks.find((policy) => policy.id === id)?.tone ?? "blue";
}
